//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by aera.rc
//
#define IDC_USING_OTHER                 3
#define IDD_ABOUTBOX                    100
#define IDC_MP_UPDATE                   101
#define IDC_CREATE_PLOT                 201
#define IDC_CREATE_LIST                 202
#define IDC_SHOWMODE                    203
#define IDC_LINEBINS                    223
#define IDD_LISTPPCOMMON                300
#define IDC_ADD_RIGHT                   302
#define IDC_ADD_LEFT                    303
#define IDC_ADD_TOP                     304
#define IDC_ADD_BOTTOM                  305
#define IDC_SUBVIEWEXCHANGE             307
#define IDC_LEFT                        308
#define IDC_LEFTALL                     309
#define IDC_RIGHT                       310
#define IDC_RIGHTALL                    311
#define IDC_UP                          312
#define IDC_DOWN                        313
#define IDC_LIST_AVIABLE                314
#define IDC_LIST_CURRENT                315
#define IDC_LIST_STATIC1                318
#define IDC_LIST_STATIC2                319
#define IDC_LIST_STATIC3                320
#define IDC_LIST_STATIC4                321
#define IDC_LIST_STATIC5                322
#define IDC_LIST_STATIC6                323
#define IDC_LIST_STATIC7                324
#define IDC_LIST_STATIC8                325
#define IDC_LIST_STATIC9                326
#define IDC_RELATIVE_TIME_MODE          351
#define IDC_NAVIGATION_MODE             352
#define IDD_PLOTPPCOMMON                510
#define IDC_PLOT_XAXE_LOG               511
#define IDC_PLOT_XAXE                   512
#define IDC_PLOT_YAXE_LOG               513
#define IDC_PLOT_YAXE                   514
#define IDC_PLOT_XAXE_MAX               515
#define IDC_PLOT_XAXE_MIN               516
#define IDC_PLOT_YAXE_MAX               517
#define IDC_PLOT_YAXE_MIN               518
#define IDC_PLOT_YAXE_AUTO              519
#define IDC_PLOT_XAXE_AUTO              520
#define IDC_SCATTER                     521
#define IDC_LINETYPE                    522
#define IDC_LINESTYLE                   524
#define IDC_COLORBYCHANNEL              525
#define IDC_PLOT_STATIC1                526
#define IDC_PLOT_STATIC2                527
#define IDR_MAINFRAME                   600
#define IDC_PROGRESS1                   601
#define ID_SAVE_PROJECT                 602
#define ID_LOAD_PROJECT                 603
#define ID_FILTER_SETTINGS              604
#define IDC_SEL_DEL                     605
#define ID_SAVE_PROJECT_AS              606
#define IDD_FILTER                      610
#define IDR_FILTER_TOOLBAR              610
#define IDR_PLOT_TOOLBAR                614
#define IDD_PAGES_RENAME                616
#define IDD_SETTINGSDLG                 617
#define IDC_HAND1                       618
#define IDC_HAND2                       619
#define IDC_ZOOMIN                      620
#define IDD_PLOT_COPYCLIPDLG            621
#define IDC_SELECT_0                    622
#define IDD_STAGES                      622
#define IDC_SELECT_1                    623
#define IDR_STAGES                      623
#define IDC_SELECT_2                    624
#define IDD_FILE_PROPERTY               626
#define IDC_EXCHANGE                    627
#define IDD_CREATE_PROJECT              628
#define IDD_REGISTRATION_CODE           629
#define IDD_NAG                         630
#define IDD_ZONAL_LOC                   631
#define IDD_LOCATION_ZONAL              631
#define IDR_LOCATION_WND                634
#define IDR_STAGE_WND                   638
#define IDR_CHANNEL_WND                 640
#define IDD_LINEAR_LOCATION             644
#define IDD_LOCATION_LINEAR             644
#define IDD_QUICK_FILTER                645
#define IDD_NEW_LOCATION                648
#define IDD_MONPAC                      649
#define ID_MONPAC_SETTINGS              650
#define IDD_PROGRESS_BAR                650
#define IDR_QF_MENU                     652
#define IDR_PLOT_MENU                   653
#define IDD_PLANAR_LOCATION             655
#define IDD_LOCATION_PLANAR             655
#define IDD_LOCATION_VESSEL             656
#define IDD_NEW_LOCATION2               657
#define IDR_MAINFRAME1                  658
#define IDR_MAINFRAME2                  659
#define IDC_PLOT_ZOOMIN                 1000
#define IDB_EXCHANGE                    1000
#define IDC_PLOT_ZOOMOUT                1001
#define IDC_PLOT_ZOOMALL                1002
#define IDC_PLOT_COPYCLIP               1003
#define IDC_PLOT_PAN                    1004
#define IDC_TILE_COPYCLIP               1005
#define IDC_TILE_SWAP                   1006
#define IDC_MP_HOLDS                    1501
#define IDC_MP_VESSEL                   1502
#define IDC_MP_STATIC1                  1503
#define IDC_MP_STATIC2                  1504
#define IDC_MP_STAGES                   1504
#define IDC_MP_RESULT                   1505
#define IDC_MP_RESULTTYPE               1505
#define IDC_MP_LOCATION                 1505
#define IDC_MP_STATIC3                  1506
#define ID_MP_COPY                      1507
#define IDC_MP_STATIC5                  1508
#define IDC_MP_STATIC4                  1509
#define IDC_MP_LOCKOUT                  1510
#define IDC_MP_STATIC7                  1511
#define IDC_FILTER_SUBSTRING            1601
#define IDC_FILTER_INSERT               1602
#define IDC_FILTER_ACCEPT               1603
#define IDC_FILTER_REJECT               1604
#define IDC_FILTER_GRID                 1605
#define IDC_FILTER_INSERT_OP            1606
#define IDC_FILTER_SELECT_OP            1607
#define IDC_FILTER_SELECT               1608
#define IDC_FILTER_CLOSE                1609
#define IDC_FILTER_APPLY                1610
#define IDC_ABOUT_STATIC1               1701
#define IDC_ABOUT_STATIC2               1702
#define IDC_ABOUT_URL1                  1703
#define IDC_ABOUT_URL2                  1704
#define IDC_ABOUT_REG1                  1705
#define IDC_ABOUT_REGINFO1              1706
#define IDC_ABOUT_REGINFO2              1707
#define IDC_PAGES_NEW_PAGE              1801
#define IDC_PAGES_DELETE_PAGE           1802
#define IDC_PAGES_NEXT_PAGE             1803
#define IDC_PAGES_PREV_PAGE             1804
#define IDC_PAGES_RENAME_PAGE           1805
#define IDC_FILTER_TOOLBAR              2000
#define IDC_FL_EDITTOOLBAR              2000
#define IDC_FL_ITEMSTOOLBAR             2001
#define IDC_APPLY                       2002
#define IDC_FL_MAINTOOLBAR              2002
#define IDC_PAGES_RENAME_EDIT           2004
#define IDC_SETTINGS_PARAMETRIC         2005
#define IDC_SETT_ADDEND1                2006
#define IDC_SETT_FACTOR1                2007
#define IDC_STATIC_PARAMETRIC1          2008
#define IDC_SETT_NAME1                  2008
#define IDC_COPYCLIP_STATIC1            2009
#define IDC_SETT_UNIT1                  2009
#define IDC_COPYCLIP_WIDTH              2010
#define IDC_SETT_NAME2                  2010
#define IDC_COYCLIP_STATIC2             2011
#define IDC_SETT_UNIT2                  2011
#define IDC_COPYCLIP_HEIGHT             2012
#define IDC_STAGES_EDIT                 2012
#define IDC_SETT_ADDEND2                2012
#define IDC_COYCLIP_STATIC3             2013
#define IDC_SETT_FACTOR2                2013
#define IDC_STAGE_LIST                  2014
#define IDC_SETT_NAME3                  2014
#define IDC_STAGE_STATIC1               2015
#define IDC_SETT_UNIT3                  2015
#define IDC_STAGE_START                 2016
#define IDC_SETT_ADDEND3                2016
#define IDC_STAGE_STATIC0               2017
#define IDC_SETT_FACTOR3                2017
#define IDC_STAGE_STATIC2               2018
#define IDC_SETT_NAME4                  2018
#define IDC_STAGE_END                   2019
#define IDC_SETT_UNIT4                  2019
#define IDC_COPYCLIP_STATIC2            2019
#define IDC_STAGE_STATIC3               2020
#define IDC_SETT_ADDEND4                2020
#define IDC_COYCLIP_STATIC4             2020
#define IDC_STAGE_NAME                  2021
#define IDC_STAGE_STATIC5               2021
#define IDC_SETT_FACTOR4                2021
#define IDC_COPYCLIP_WIDTHMM            2021
#define IDC_STAGE_STATIC4               2022
#define IDC_STAGE_NAME2                 2022
#define IDC_COYCLIP_STATIC5             2022
#define IDC_STAGE_CONTENTS              2023
#define IDC_COPYCLIP_HEIGHTMM           2023
#define IDC_STAGE_TREE                  2024
#define IDC_STAGE_PLOTPOS               2025
#define IDC_STAGE_PLOTPOS2              2026
#define IDC_MP_STATIC6                  2026
#define IDC_MP_GRID                     2027
#define IDC_SET_PARAMETRIC              2028
#define IDC_SET_PARAMETRIC1             2028
#define IDC_FL_SUBLIST                  2029
#define IDC_SET_PARAMETRIC2             2029
#define IDC_PROP_TITLE                  2030
#define IDC_SET_PARAMETRIC3             2030
#define IDC_PROP_DATE                   2031
#define IDC_SET_PARAMETRIC4             2031
#define IDC_PROP_PRODUCT                2032
#define IDC_MP_EVAL                     2034
#define IDC_MP_INTENS                   2035
#define IDC_USING_DEFAULT               2035
#define IDC_MP_GRAPH                    2036
#define IDC_SHOW_TDD                    2036
#define IDC_REGISTRATION_CODE           2037
#define IDC_MP_TYPE1                    2037
#define IDC_AERA_ICON                   2038
#define IDC_MP_TYPE2                    2038
#define IDC_REGISTRATION_INFO           2039
#define IDC_MP_TYPE3                    2039
#define IDC_ZONAL_LOCKOUT               2040
#define IDC_MP_IT_EVAL                  2041
#define IDC_MP_IT_TEST                  2042
#define IDC_ZL_USE_PEAK_TIME            2045
#define IDC_ZL_USE_FRONT_TIME           2046
#define IDC_EDIT1                       2046
#define IDC_LL_VELOCITY                 2046
#define IDC_QF_TEXT                     2046
#define IDC_PL_DIAM                     2046
#define IDC_LIST1                       2047
#define IDC_ZL_GRID                     2047
#define IDC_ZL_GRID1                    2047
#define IDC_LL_CHLIST                   2048
#define IDC_STATIC1                     2048
#define IDC_INSERT_POINT                2049
#define IDC_PP_USE_LOCATION             2050
#define IDC_LP_USE_LOCATION             2050
#define IDC_PP_LOCATION                 2051
#define IDC_LP_LOCATION                 2051
#define IDC_LP_NAV_MODE                 2052
#define IDC_PP_USE_CLUSTERS             2052
#define IDC_LP_REL_TIME                 2053
#define IDC_LP_NAV_MODE2                2054
#define IDC_LP_TIME1                    2055
#define IDC_LP_TIME2                    2056
#define IDC_FL_CHART                    2056
#define IDC_FL_CHART2                   2057
#define IDC_FL_RESTORE                  2058
#define IDC_CR_DEFAULT                  2059
#define IDC_FL_CHART3                   2059
#define IDC_CR_OTHER                    2060
#define IDC_FL_CHART_2                  2061
#define IDC_CR_CURRENT                  2061
#define IDC_FL_CHART2_2                 2062
#define IDC_NL_ZONAL                    2062
#define IDC_FL_CHART3_2                 2063
#define IDC_NL_LINEAR                   2063
#define IDC_NL_PLANAR                   2064
#define IDC_LL_UNITS                    2064
#define IDC_QF_SEL1                     2065
#define IDC_NL_VESSEL                   2065
#define IDC_QF_SEL2                     2066
#define IDC_QF_SEL3                     2067
#define IDC_QF_TIME                     2069
#define IDC_QF_NEDIT1                   2070
#define IDC_QF_NEDIT2                   2071
#define IDC_QF_BEFORE                   2072
#define IDC_QF_AFTER                    2073
#define IDC_QF_NAME                     2074
#define IDC_LL_ADD                      2076
#define IDC_LL_REMOVE                   2077
#define IDC_VL_ADD_PART                 2078
#define IDC_STATIC2                     2079
#define IDC_VL_REMOVE_PART              2080
#define IDC_STATIC3                     2081
#define IDC_VL_PARTS                    2082
#define IDC_VL_CHLIST                   2083
#define IDC_VL_ADD                      2084
#define IDC_VL_REMOVE                   2085
#define ID_DEFAULTENGLISH               32770
#define ID_LOAD_LAYOUT                  32790
#define ID_SAVE_LAYOUT                  32791
#define ID_MRU_LAYOUTS1                 32792
#define ID_MRU_LAYOUTSN                 32812
#define ID_MRU_PROJECTS1                32813
#define ID_MRU_PROJECTSN                32833
#define IDC_VIEW_CHANNELS               32839
#define IDC_EDIT_ALL                    32840
#define IDM_RESIZEWINDOWX               32841
#define ID_BUTTON32842                  32842
#define IDC_QF_INSERT_VAR               32842
#define ID_BUTTON32843                  32843
#define IDC_QF_INSERT_OPER              32843
#define ID_BUTTON32844                  32844
#define IDC_QF_INSERT_OR                32844
#define IDC_EDIT_INVERT                 32845
#define IDC_SETTINGS_OPTIONS            32856
#define IDC_VIEW_STAGES                 32859
#define ID_APPEND_STAGE                 32860
#define ID_DELETE_STAGE                 32861
#define ID_RENAME_STAGE                 32863
#define IDC_VIEW_STAGES1                32864
#define IDC_VIEW_ALLTAB                 32865
#define IDC_VIEW_ALLTABS                -32670
#define ID_BUTTON32867                  32867
#define IDC_QF_INSERT_AND               32867
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_FLT_NORMAL                   32872
#define ID_FLT_EXCEPT                   32873
#define ID_ARRANGEWINDOWS               32874
#define IDC_PROPERTIES                  32875
#define IDC_REGISTER                    32876
#define IDC_ORDER_SOFTWARE              32877
#define IDC_LOCWIN_PROPERTY             32878
#define ID_STAGE_PROPERTY               32880
#define ID_BUTTON32881                  32881
#define IDC_VIEW_LOCATION               32882
#define ID_BUTTON32883                  32883
#define ID_BUTTON32884                  32884
#define ID_ADDARRANGEWINDOW             32885
#define ID_FILTER_SETTINGS2             32886
#define IDC_LOCWIN_INSERT               32888
#define IDC_LOCWIN_DELETE               32889
#define IDC_SEL_INVERT                  32890
#define IDC_QF_SAVE                     32896
#define IDC_QF_LOAD                     32897
#define IDC_QF_MRU_FIRST                32898
#define IDC_PLOT_NORMAL                 32901
#define ID_BUTTON32902                  32902
#define ID_VIEW_PLOT_TOOLBAR            32903
#define ID_BUTTON32904                  32904
#define IDC_RELOAD_FILE                 32905
#define IDC_QF_MRU_LAST                 32920
#define IDC_QF_MRUV_FIRST               32940
#define ID_LOAD_TEMPLATE                32941
#define IDC_WINDOWS_800_600             32942
#define IDC_WINDOWS_1024_768            32943

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        657
#define _APS_NEXT_COMMAND_VALUE         32944
#define _APS_NEXT_CONTROL_VALUE         2086
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
